controller_manager:
    ros__parameters:
        use_sim_time: true

        update_rate: 1000
            
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        imu_sensor_broadcaster:
            type: imu_sensor_broadcaster/IMUSensorBroadcaster

        pd_controller:
            type: pd_controller/PDController


joint_state_broadcaster:
    ros__parameters:
        use_sim_time: true

        joints:
            - LF_HFE
            - LF_KFE
            - LH_HFE
            - LH_KFE
            - RF_HFE
            - RF_KFE
            - RH_HFE
            - RH_KFE
        interfaces:
            - position
            - velocity
            - effort


imu_sensor_broadcaster:
    ros__parameters:
        use_sim_time: true
        sensor_name: imu_sensor
        frame_id: base


pd_controller:
    ros__parameters:
        use_sim_time: true

        joint_names:
            - LF_HFE
            - LF_KFE
            - LH_HFE
            - LH_KFE
            - RF_HFE
            - RF_KFE
            - RH_HFE
            - RH_KFE

        initialization_time: 2.5
        initialization_phases:
            - 0.5
            - 0.5

        q1:
            - -2.
            -  3.
            -  2.
            - -3.
            -  2.
            - -3.
            - -2.
            -  3.

        q2:
            - -4.
            -  5.
            -  4.
            - -5.
            -  4.
            - -5.
            - -4.
            -  5.

        PD_proportional:
            - 20.0
            - 10.0
            - 20.0
            - 10.0
            - 20.0
            - 10.0
            - 20.0
            - 10.0
        PD_derivative:
            - 2.0
            - 0.2
            - 2.0
            - 0.2
            - 2.0
            - 0.2
            - 2.0
            - 0.2
